name: silly_gun_ultimate
description: "A new Flutter project."
publish_to: "none"
version: 1.2.1+5

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.5
  animated_text_kit: ^4.3.0
  animations: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  share_plus: ^13.1.0
  shared_preferences: ^2.5.5
  shimmer: ^3.0.0
  stylish_bottom_bar: ^1.1.1
  url_launcher: ^6.3.2
  video_player: ^2.11.1
  wallpaper_manager_plus: ^2.0.3
  google_fonts: ^6.2.1
  firebase_core: ^4.10.0
  google_mobile_ads: ^8.0.0
  firebase_remote_config: ^6.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/utils/
    - assets/fonts/
    - assets/splash/
  fonts:
    - family: NotoSerif
      fonts:
        - asset: assets/fonts/NotoSerif/NotoSerif-Light.ttf
          weight: 300

        - asset: assets/fonts/NotoSerif/NotoSerif-Medium.ttf
          weight: 500

        - asset: assets/fonts/NotoSerif/NotoSerif-Bold.ttf
          weight: 700

        - asset: assets/fonts/NotoSerif/NotoSerif-ExtraBold.ttf
          weight: 800
